#!/bin/bash
total 20
-rwxr--r-- 1 root root 16 Sep  2 05:01 0-current_working_directory
-rwxr--r-- 1 root root 15 Sep  2 09:00 1-listit
-rwxr--r-- 1 root root 15 Sep  2 09:41 2-bring_me_home
-rw-r--r-- 1 root root 12 Sep  2 11:33 3-listfiles
-rw-r--r-- 1 root root 63 Sep  2 10:08 README.md
